version: '3'
services:
  jenkins:
    container_name: $CONTAINER_NAME
    image: $IMAGE_JENKINS
    ports:
      - "8080:8080"
    volumes:
      - $PWD/jenkins_home:/var/jenkins_home
networks:
  default:
    external:
      name: $DOCKER_NETWORK